name: Move new issues into Triage

on:
  issues:
    types: [opened, labeled]

jobs:
  add-to-triage:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.2.4
        with:
          project: Test project
          column: "To do: suggestion or enhancement"
          repo-token: ${{ secrets.GITHUBTEACHER_TOKEN }}
  
  add-issue-to-project:
    runs-on: ubuntu-latest
    steps:
      - if: github.event.label.name == 'bug'
        uses: alex-page/github-project-automation-plus@v0.2.4
        with:
          project: Test project
          column: "Needs to be replicated / tested"
          repo-token: ${{ secrets.GITHUBTEACHER_TOKEN }}

      - if: github.event.label.name == 'enhancement'
        uses: alex-page/github-project-automation-plus@v0.2.4
        with:
          project: Test project
          column: "To do: suggestion or enhancement"
          repo-token: ${{ secrets.GITHUBTEACHER_TOKEN }}
          
      - if: github.event.label.name == null
        uses: alex-page/github-project-automation-plus@v0.2.4
        with:
          project: Test project
          column: "Triage"
          repo-token: ${{ secrets.GITHUBTEACHER_TOKEN }}
