name: Move new issues into Triage

on:
  issues: 
    types: [opened]

jobs:
  add-issue-to-triage:
    runs-on: ubuntu-latest
    steps:
      - name: "Add issue to project triage column"
        if: github.event.label.name == null
        uses: alex-page/github-project-automation-plus@v0.2.4
        with:
          project: Test project
          column: "Triage"
          repo-token: ${{ secrets.GITHUBTEACHER_TOKEN }}
